name: ClashForge

on:
  schedule:
   - cron: '0 7-22/5 * * *'
  push:
    paths-ignore:
      - '**'
  workflow_dispatch:

jobs:
  run_demo_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # 转到 Settings > Secrets and variables > Actions
          # 点击 New repository secret，添加 Secret，名称为 BOT，输入你的token
          token: ${{ secrets.BOT }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'

      - name: Install requirements.txt
        run: |
          pip install -r ./requirements.txt

      - name: Run ClashForge.py
        run: python ClashForge.py

      - name: Commit and push file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/clash_config.yaml
          git commit -m "update" || echo "No changes to commit"
          git push https://${{ secrets.BOT }}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.BOT }}
          API_TOKEN_GITHUB: ${{ secrets.BOT }}
        with:
          source-directory: 'dist'
          destination-github-username: 'leiqlxk'
          destination-repository-name: 'config'
          user-email: lql@qq.com
          target-branch: main
