name: ClashForge

on:
  schedule:
   - cron: '0 7-22/5 * * *'
  push:
    paths-ignore:
      - '**'
  workflow_dispatch:

jobs:
  run_demo_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # 转到 Settings > Secrets and variables > Actions
          # 点击 New repository secret，添加 Secret，名称为 BOT，输入你的token
          token: ${{ secrets.BOT }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'

      - name: Install requirements.txt
        run: |
          pip install -r ./requirements.txt

      - name: Run ClashForge.py
        run: python ClashForge.py

      - name: Commit and push file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/clash_config.yaml
          git commit -m "update" || echo "No changes to commit"
          git push https://${{ secrets.BOT }}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git

      - name: to target repo
        uses: s0/git-publish-subdir-action@develop
        env:
          # 换成自己的目标仓库
          REPO: git@github.com:leiqlxk/config.git
          # 目标分支
          BRANCH: main 
          # 要推送的目录
          FOLDER: dist 
          # 保存在secrets里面生成的ssh私钥
          SSH_PRIVATE_KEY: ${{ secrets.BOT }}
